# Generated by Django 3.0.8 on 2020-07-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemCenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.CharField(default='NotGiven', max_length=500),
            preserve_default=False,
        ),
    ]
