# Generated by Django 3.0.8 on 2020-07-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemCenter', '0002_question_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='submittedExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
            ],
        ),
    ]
