# Generated by Django 3.0.8 on 2020-07-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemCenter', '0004_submittedexams_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='submitAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer_text', models.CharField(max_length=500)),
            ],
        ),
    ]
